/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion2.proyectofinal.view;

import ni.edu.uni.programacion2.proyectofinal.view.panels.PnlVender;

/**
 *
 * @author Ariel Roa
 */
public class IFrmVender extends javax.swing.JInternalFrame {

    private PnlVender pnlVender;
    /**
     * Creates new form IFrmVender
     */
    public IFrmVender() {
        initComponents();
    }

    public PnlVender getPnlVender() {
        return pnlVender;
    }

    public void setPnlVender(PnlVender pnlVender) {
        this.pnlVender = pnlVender;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        pnlContenido.setLayout(new java.awt.BorderLayout());
        pnlVender = new PnlVender();
        pnlContenido.add(pnlVender);
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
