/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion2.proyectofinal.view;

import ni.edu.uni.programacion2.proyectofinal.view.panels.PnlMostrarInventario;

/**
 *
 * @author Ariel Roa
 */
public class IFrmMostrarInventario extends javax.swing.JInternalFrame {

    private PnlMostrarInventario pnlMostrarInventario;
    /**
     * Creates new form JFrmMostrarInventario
     */
    public IFrmMostrarInventario() {
        initComponents();
    }

    public PnlMostrarInventario getPnlMostrarInventario() {
        return pnlMostrarInventario;
    }

    public void setPnlMostrarInventario(PnlMostrarInventario pnlMostrarInventario) {
        this.pnlMostrarInventario = pnlMostrarInventario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mostrar inventario");

        pnlContenido.setLayout(new java.awt.BorderLayout());
        pnlMostrarInventario = new PnlMostrarInventario();
        pnlContenido.add(pnlMostrarInventario);
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
