/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion2.proyectofinal.view;

import ni.edu.uni.programacion2.proyectofinal.view.panels.PnlMostrarCatalogo;

/**
 *
 * @author Ariel Roa
 */
public class IFrmMostrarCatalogo extends javax.swing.JInternalFrame {

    private PnlMostrarCatalogo pnlMostrarCatalogo;
    /**
     * Creates new form IFrmMostrarCatalogo
     */
    public IFrmMostrarCatalogo() {
        initComponents();
    }

    public PnlMostrarCatalogo getPnlMostrarCatalogo() {
        return pnlMostrarCatalogo;
    }

    public void setPnlMostrarCatalogo(PnlMostrarCatalogo pnlMostrarCatalogo) {
        this.pnlMostrarCatalogo = pnlMostrarCatalogo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mostrar catálogo");

        pnlContenido.setLayout(new java.awt.BorderLayout());
        pnlMostrarCatalogo = new PnlMostrarCatalogo();
        pnlContenido.add(pnlMostrarCatalogo);
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
