/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion2.proyectofinal.view;

import ni.edu.uni.programacion2.proyectofinal.view.panels.PnlMostrarFactura;

/**
 *
 * @author Ariel Roa
 */
public class IFrmMostrarFactura extends javax.swing.JInternalFrame {

    private PnlMostrarFactura pnlMostrarFactura;
    /**
     * Creates new form IFrmMostrarFactura
     */
    public IFrmMostrarFactura() {
        initComponents();
    }

    public PnlMostrarFactura getPnlMostrarFactura() {
        return pnlMostrarFactura;
    }

    public void setPnlMostrarFactura(PnlMostrarFactura pnlMostrarFactura) {
        this.pnlMostrarFactura = pnlMostrarFactura;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mostrar factura");

        pnlContenido.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);
        pnlMostrarFactura = new PnlMostrarFactura();
        pnlContenido.add(pnlMostrarFactura);

        setBounds(0, 0, 610, 430);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
