/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion2.proyectofinal.view;

import ni.edu.uni.programacion2.proyectofinal.view.panels.PnlComprar;

/**
 *
 * @author Ariel Roa
 */
public class IFrmComprar extends javax.swing.JInternalFrame {

    private PnlComprar pnlComprar;
    /**
     * Creates new form IFrmComprar
     */
    public IFrmComprar() {
        initComponents();
    }

    public PnlComprar getPnlComprar() {
        return pnlComprar;
    }

    public void setPnlComprar(PnlComprar pnlComprar) {
        this.pnlComprar = pnlComprar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Comprar");

        pnlContenido.setLayout(new java.awt.BorderLayout());
        pnlComprar = new PnlComprar();
        pnlContenido.add(pnlComprar);
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
